// <auto-generated />
using System;
using FacultySports.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FacultySports.Infrastructure.Migrations
{
    [DbContext(typeof(SportsDbContext))]
    partial class SportsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompetitionParticipant", b =>
                {
                    b.Property<int>("CompetitionId")
                        .HasColumnType("integer")
                        .HasColumnName("competition_id");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer")
                        .HasColumnName("participant_id");

                    b.HasKey("CompetitionId", "ParticipantId")
                        .HasName("competition_participant_pkey");

                    b.HasIndex("ParticipantId");

                    b.ToTable("competition_participant", (string)null);
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("cities_pkey");

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<int?>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("competitions_pkey");

                    b.HasIndex("LocationId");

                    b.HasIndex("SectionId");

                    b.HasIndex("StatusId");

                    b.ToTable("competitions", (string)null);
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.CompetitionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("competition_statuses_pkey");

                    b.HasIndex(new[] { "Code" }, "competition_statuses_code_key")
                        .IsUnique();

                    b.ToTable("competition_statuses", (string)null);
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("integer")
                        .HasColumnName("participant_id");

                    b.Property<int>("SectionId")
                        .HasColumnType("integer")
                        .HasColumnName("section_id");

                    b.HasKey("Id")
                        .HasName("enrollments_pkey");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("SectionId");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityId")
                        .HasColumnType("integer")
                        .HasColumnName("city_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("locations_pkey");

                    b.HasIndex("CityId");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("participants_pkey");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_week");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("schedules_pkey");

                    b.HasIndex("LocationId");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_id");

                    b.HasKey("Id")
                        .HasName("sections_pkey");

                    b.HasIndex("ScheduleId");

                    b.ToTable("sections", (string)null);
                });

            modelBuilder.Entity("CompetitionParticipant", b =>
                {
                    b.HasOne("FacultySports.Domain.Entities.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("competition_participant_competition_id_fkey");

                    b.HasOne("FacultySports.Domain.Entities.Participant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("competition_participant_participant_id_fkey");
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Competition", b =>
                {
                    b.HasOne("FacultySports.Domain.Entities.Location", "Location")
                        .WithMany("Competitions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("competitions_location_id_fkey");

                    b.HasOne("FacultySports.Domain.Entities.Section", "Section")
                        .WithMany("Competitions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("competitions_section_id_fkey");

                    b.HasOne("FacultySports.Domain.Entities.CompetitionStatus", "Status")
                        .WithMany("Competitions")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("competitions_status_id_fkey");

                    b.Navigation("Location");

                    b.Navigation("Section");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("FacultySports.Domain.Entities.Participant", "Participant")
                        .WithMany("Enrollments")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("enrollments_participant_id_fkey");

                    b.HasOne("FacultySports.Domain.Entities.Section", "Section")
                        .WithMany("Enrollments")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("enrollments_section_id_fkey");

                    b.Navigation("Participant");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Location", b =>
                {
                    b.HasOne("FacultySports.Domain.Entities.City", "City")
                        .WithMany("Locations")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("locations_city_id_fkey");

                    b.Navigation("City");
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Schedule", b =>
                {
                    b.HasOne("FacultySports.Domain.Entities.Location", "Location")
                        .WithMany("Schedules")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("schedules_location_id_fkey");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Section", b =>
                {
                    b.HasOne("FacultySports.Domain.Entities.Schedule", "Schedule")
                        .WithMany("Sections")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("sections_schedule_id_fkey");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.City", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.CompetitionStatus", b =>
                {
                    b.Navigation("Competitions");
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Location", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Participant", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Schedule", b =>
                {
                    b.Navigation("Sections");
                });

            modelBuilder.Entity("FacultySports.Domain.Entities.Section", b =>
                {
                    b.Navigation("Competitions");

                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
